import {
  BONNY_FURY,
  BONNY_FURY_SKILL,
  BONNY_NORMAL,
  BONNY_NORMAL_SKILL,
  BONNY_POWER,
  BONNY_POWER_SKILL,
  CHRIS_FURY,
  CHRIS_FURY_SKILL,
  CHRIS_NORMAL,
  CHRIS_NORMAL_SKILL,
  CHRIS_POWER,
  CHRIS_POWER_SKILL,
  CRO_FURY,
  CRO_FURY_SKILL,
  CRO_NORMAL,
  CRO_NORMAL_SKILL,
  CRO_POWER,
  CRO_POWER_SKILL,
  ELLY_FURY,
  ELLY_FURY_SKILL,
  FIONA_NORMAL,
  FIONA_NORMAL_SKILL,
  FIONA_POWER,
  FIONA_POWER_SKILL,
  GOLIATH_FURY,
  GOLIATH_FURY_SKILL,
  GOLIATH_NORMAL,
  GOLIATH_NORMAL_SKILL,
  GOLIATH_POWER,
  GOLIATH_POWER_SKILL,
  HELLGA_NORMAL,
  HELLGA_NORMAL_SKILL,
  HELLGA_POWER,
  HELLGA_POWER_SKILL,
  HIKARU_FURY,
  HIKARU_FURY_SKILL,
  HIKARU_NORMAL,
  HIKARU_NORMAL_SKILL,
  HIKARU_POWER,
  HIKARU_POWER_SKILL,
  KANG_FURY,
  KANG_FURY_SKILL,
  KANG_NORMAL,
  KANG_NORMAL_SKILL,
  KANG_POWER,
  KANG_POWER_SKILL,
  KYLE_FURY,
  KYLE_FURY_SKILL,
  KYLE_NORMAL,
  KYLE_NORMAL_SKILL,
  KYLE_POWER,
  KYLE_POWER_SKILL,
  MARSHAL_FURY,
  MARSHAL_FURY_SKILL,
  MARSHAL_NORMAL,
  MARSHAL_NORMAL_SKILL,
  MARSHAL_POWER,
  MARSHAL_POWER_SKILL,
  RAIZIN_FURY,
  RAIZIN_FURY_SKILL,
  RAIZIN_NORMAL,
  RAIZIN_NORMAL_SKILL,
  RAIZIN_POWER,
  RAIZIN_POWER_SKILL,
  RICKY_FURY,
  RICKY_FURY_SKILL,
  RYUSEI_FURY,
  RYUSEI_FURY_SKILL,
  RYUSEI_NORMAL,
  RYUSEI_NORMAL_SKILL,
  RYUSEI_POWER,
  RYUSEI_POWER_SKILL,
  SARUNBI_NORMAL,
  SARUNBI_NORMAL_SKILL,
  SARUNBI_POWER,
  SARUNBI_POWER_SKILL,
  TIAN_FURY,
  TIAN_FURY_SKILL,
  TIAN_NORMAL,
  TIAN_NORMAL_SKILL,
  TIAN_POWER,
  TIAN_POWER_SKILL,
  TOM_NORMAL,
  TOM_NORMAL_SKILL,
  TOM_POWER,
  TOM_POWER_SKILL,
  XIAH_FURY,
  XIAH_FURY_SKILL,
  XIAH_NORMAL,
  XIAH_NORMAL_SKILL,
  XIAH_POWER,
  XIAH_POWER_SKILL,
} from "@public/index";

export const TOP_OFFSET = 66;

export const HEROES_NORMAL = [
  {
    id: "1",
    name: "cro",
    image: CRO_NORMAL,
    skill: CRO_NORMAL_SKILL,
  },
  {
    id: "2",
    name: "bonny",
    image: BONNY_NORMAL,
    skill: BONNY_NORMAL_SKILL,
  },
  {
    id: "3",
    name: "chris",
    image: CHRIS_NORMAL,
    skill: CHRIS_NORMAL_SKILL,
  },
  {
    id: "4",
    name: "fiona",
    image: FIONA_NORMAL,
    skill: FIONA_NORMAL_SKILL,
  },
  {
    id: "5",
    name: "goliath",
    image: GOLIATH_NORMAL,
    skill: GOLIATH_NORMAL_SKILL,
  },
  {
    id: "6",
    name: "hellga",
    image: HELLGA_NORMAL,
    skill: HELLGA_NORMAL_SKILL,
  },
  {
    id: "7",
    name: "hikaru",
    image: HIKARU_NORMAL,
    skill: HIKARU_NORMAL_SKILL,
  },
  {
    id: "8",
    name: "kang",
    image: KANG_NORMAL,
    skill: KANG_NORMAL_SKILL,
  },
  {
    id: "9",
    name: "kyle",
    image: KYLE_NORMAL,
    skill: KYLE_NORMAL_SKILL,
  },
  {
    id: "10",
    name: "marshal",
    image: MARSHAL_NORMAL,
    skill: MARSHAL_NORMAL_SKILL,
  },
  {
    id: "11",
    name: "raizin",
    image: RAIZIN_NORMAL,
    skill: RAIZIN_NORMAL_SKILL,
  },
  {
    id: "12",
    name: "ryusei",
    image: RYUSEI_NORMAL,
    skill: RYUSEI_NORMAL_SKILL,
  },
  {
    id: "13",
    name: "sarunbi",
    image: SARUNBI_NORMAL,
    skill: SARUNBI_NORMAL_SKILL,
  },
  {
    id: "14",
    name: "tian",
    image: TIAN_NORMAL,
    skill: TIAN_NORMAL_SKILL,
  },
  {
    id: "15",
    name: "tom",
    image: TOM_NORMAL,
    skill: TOM_NORMAL_SKILL,
  },
  {
    id: "16",
    name: "xiah",
    image: XIAH_NORMAL,
    skill: XIAH_NORMAL_SKILL,
  },
];

export const HEROES_POWER = [
  {
    id: "1",
    name: "cro",
    image: CRO_POWER,
    skill: CRO_POWER_SKILL,
  },
  {
    id: "2",
    name: "bonny",
    image: BONNY_POWER,
    skill: BONNY_POWER_SKILL,
  },
  {
    id: "3",
    name: "chris",
    image: CHRIS_POWER,
    skill: CHRIS_POWER_SKILL,
  },
  {
    id: "4",
    name: "fiona",
    image: FIONA_POWER,
    skill: FIONA_POWER_SKILL,
  },
  {
    id: "5",
    name: "goliath",
    image: GOLIATH_POWER,
    skill: GOLIATH_POWER_SKILL,
  },
  {
    id: "6",
    name: "hellga",
    image: HELLGA_POWER,
    skill: HELLGA_POWER_SKILL,
  },
  {
    id: "7",
    name: "hikaru",
    image: HIKARU_POWER,
    skill: HIKARU_POWER_SKILL,
  },
  {
    id: "8",
    name: "kang",
    image: KANG_POWER,
    skill: KANG_POWER_SKILL,
  },
  {
    id: "9",
    name: "kyle",
    image: KYLE_POWER,
    skill: KYLE_POWER_SKILL,
  },
  {
    id: "10",
    name: "marshal",
    image: MARSHAL_POWER,
    skill: MARSHAL_POWER_SKILL,
  },
  {
    id: "11",
    name: "raizin",
    image: RAIZIN_POWER,
    skill: RAIZIN_POWER_SKILL,
  },
  {
    id: "12",
    name: "ryusei",
    image: RYUSEI_POWER,
    skill: RYUSEI_POWER_SKILL,
  },
  {
    id: "13",
    name: "sarunbi",
    image: SARUNBI_POWER,
    skill: SARUNBI_POWER_SKILL,
  },
  {
    id: "14",
    name: "tian",
    image: TIAN_POWER,
    skill: TIAN_POWER_SKILL,
  },
  {
    id: "15",
    name: "tom",
    image: TOM_POWER,
    skill: TOM_POWER_SKILL,
  },
  {
    id: "16",
    name: "xiah",
    image: XIAH_POWER,
    skill: XIAH_POWER_SKILL,
  },
];

export const HEROES_FURY = [
  {
    id: "1",
    name: "cro",
    image: CRO_FURY,
    skill: CRO_FURY_SKILL,
  },
  {
    id: "2",
    name: "bonny",
    image: BONNY_FURY,
    skill: BONNY_FURY_SKILL,
  },
  {
    id: "3",
    name: "chris",
    image: CHRIS_FURY,
    skill: CHRIS_FURY_SKILL,
  },
  {
    id: "4",
    name: "elly",
    image: ELLY_FURY,
    skill: ELLY_FURY_SKILL,
  },
  {
    id: "5",
    name: "goliath",
    image: GOLIATH_FURY,
    skill: GOLIATH_FURY_SKILL,
  },
  {
    id: "6",
    name: "hikaru",
    image: HIKARU_FURY,
    skill: HIKARU_FURY_SKILL,
  },
  {
    id: "7",
    name: "kang",
    image: KANG_FURY,
    skill: KANG_FURY_SKILL,
  },
  {
    id: "8",
    name: "kyle",
    image: KYLE_FURY,
    skill: KYLE_FURY_SKILL,
  },
  {
    id: "9",
    name: "marshal",
    image: MARSHAL_FURY,
    skill: MARSHAL_FURY_SKILL,
  },
  {
    id: "10",
    name: "raizin",
    image: RAIZIN_FURY,
    skill: RAIZIN_FURY_SKILL,
  },
  {
    id: "11",
    name: "ryusei",
    image: RYUSEI_FURY,
    skill: RYUSEI_FURY_SKILL,
  },
  {
    id: "12",
    name: "ricky",
    image: RICKY_FURY,
    skill: RICKY_FURY_SKILL,
  },

  {
    id: "13",
    name: "tian",
    image: TIAN_FURY,
    skill: TIAN_FURY_SKILL,
  },

  {
    id: "14",
    name: "xiah",
    image: XIAH_FURY,
    skill: XIAH_FURY_SKILL,
  },
];
